-- local null_ls = require("null-ls")
--
-- -- register any number of sources simultaneously
-- local sources = {
--     ..., -- add to your other sources
--     require("typescript.extensions.null-ls.code-actions"),
--     null_ls.builtins.diagnostics.eslint_d,
--     -- null_ls.builtins.formatting.stylua,
--     null_ls.builtins.formatting.prettierd,
--     -- null_ls.builtins.formatting.black,
--     -- null_ls.builtins.diagnostics.write_good,
--     null_ls.builtins.code_actions.gitsigns,
-- }
--
-- null_ls.setup({
--     sources = sources,
--     on_attach = function(client, bufnr)
--         if client.supports_method("textDocument/formatting") then
--             vim.api.nvim_buf_set_keymap(bufnr, 'n', '<space>f', '<cmd>lua vim.lsp.buf.format { async = true }<CR>',
--                 { noremap = true, silent = true })
--         end
--     end,
-- })
